name: BentoBox-MagicCobblestoneGenerator
main: world.bentobox.magiccobblestonegenerator.StoneGeneratorPladdon
version: ${project.version}${build.number}
api-version: "1.21"

authors: [BONNe, tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
