//
// Created by BONNe
// Copyright - 2024
//


package world.bentobox.magiccobblestonegenerator.database.objects;


import com.google.gson.annotations.Expose;


/**
 * This object stores exhaustion tracking data for a single generator tier on a single island. It keeps track of how
 * many blocks were generated during the current exhaustion period, when that period started, and until when the
 * generator is on cooldown after being exhausted.
 */
public class GeneratorExhaustionData
{
    /**
     * Default constructor.
     */
    public GeneratorExhaustionData()
    {
    }


    /**
     * This method returns the generatedCount value.
     *
     * @return the value of generatedCount.
     */
    public long getGeneratedCount()
    {
        return generatedCount;
    }


    /**
     * This method sets the generatedCount value.
     *
     * @param generatedCount the generatedCount new value.
     */
    public void setGeneratedCount(long generatedCount)
    {
        this.generatedCount = generatedCount;
    }


    /**
     * This method returns the periodStart value.
     *
     * @return the value of periodStart.
     */
    public long getPeriodStart()
    {
        return periodStart;
    }


    /**
     * This method sets the periodStart value.
     *
     * @param periodStart the periodStart new value.
     */
    public void setPeriodStart(long periodStart)
    {
        this.periodStart = periodStart;
    }


    /**
     * This method returns the cooldownUntil value.
     *
     * @return the value of cooldownUntil.
     */
    public long getCooldownUntil()
    {
        return cooldownUntil;
    }


    /**
     * This method sets the cooldownUntil value.
     *
     * @param cooldownUntil the cooldownUntil new value.
     */
    public void setCooldownUntil(long cooldownUntil)
    {
        this.cooldownUntil = cooldownUntil;
    }


// ---------------------------------------------------------------------
// Section: Variables
// ---------------------------------------------------------------------

    /**
     * Number of blocks generated by the generator during the current exhaustion period.
     */
    @Expose
    private long generatedCount = 0;

    /**
     * Timestamp (epoch millis) when the current exhaustion period started.
     */
    @Expose
    private long periodStart = 0;

    /**
     * Timestamp (epoch millis) until which the generator is on cooldown. 0 means the generator is not on cooldown.
     */
    @Expose
    private long cooldownUntil = 0;
}
